default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME") { 'mirzalazuardi' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'password' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hometime_reservation_development

test:
  <<: *default
  database: hometime_reservation_test

production:
  <<: *default
  database: hometime_reservation_production
  username: hometime_reservation
  password: <%= ENV['HOMETIME_RESERVATION_DATABASE_PASSWORD'] %>
